name: Update Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Updates daily at midnight UTC
  workflow_dispatch:      # Lets you trigger it manually

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: m0hammedsahal  # Replace with your username
          svg_output_path: "dist/github-contribution-grid-snake.svg"
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
